=== autonubil/codex/schemas/json/uri.json
{
  "$id": "https://www.github.com/robcowart/codex/blob/master/schemas/json/uri.json#",
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "title": "URI",
  "description": "A Uniform Resource Identifier (URI - RFC3986) is a string of characters that unambiguously identifies a particular resource.",
  "required": [
    "ref"
  ],
  "properties": {
    "ref": {
      "type": "string",
      "examples": [
        "http://username:password@demo.north.codex-test.org:9000/app/dashboard/eaa84cd0?_g=h@22cdd26&_a=h@ed7af2a#noc"
      ],
      "title": "reference",
      "description": "The complete Uniform Resource Identifier (URI)."
    },
    "scheme": {
      "type": "string",
      "examples": [
        "http"
      ],
      "title": "scheme",
      "description": "Each URI begins with a scheme name that refers to a specification for assigning identifiers within that scheme. As such, the URI syntax is a federated and extensible naming system wherein each scheme's specification may further restrict the syntax and semantics of identifiers using that scheme."
    },
    "authority": {
      "type": "string",
      "examples": [
        "username:password@demo.north.codex-test.org:9000"
      ],
      "title": "authority",
      "description": "Many URI schemes include a hierarchical element for a naming authority. The generic syntax provides a common means for distinguishing an authority based on a registered name or server address, along with optional port and user information. The authority component is preceded by a double slash (//) and is terminated by the next slash (/), question mark (?), or number sign (#), or by the end of the URI."
    },
    "userinfo": {
      "type": "object",
      "properties": {
        "user": {
          "type": "string",
          "examples": [
            "username"
          ],
          "title": "user",
          "description": "The user name portion of the userinfo subcomponent."
        },
        "password": {
          "type": "string",
          "examples": [
            "password"
          ],
          "title": "password",
          "description": "The password portion of the userinfo subcomponent."
        }
      },
      "required": [
        "user",
        "password"
      ],
      "additionalProperties": false
    },
    "host": {
      "$ref": "https://www.github.com/robcowart/codex/blob/master/schemas/json/host.json#",
      "examples": [
        "demo.north.codex-test.org"
      ],
      "title": "host",
      "description": "The host subcomponent of authority is identified by an IP literal encapsulated within square brackets, an IPv4 address in dotted-decimal form, or a registered name."
    },
    "port": {
      "type": "integer",
      "examples": [
        9000
      ],
      "title": "port",
      "description": "The port subcomponent of authority is designated by an optional port number in decimal following the host and delimited from it by a single colon (:) character. A scheme may define a default port. For example, the http scheme defines a default port of 80, corresponding to its reserved TCP port number. The type of port designated by the port number (e.g., TCP, UDP, SCTP) is defined by the URI scheme."
    },
    "path": {
      "type": "string",
      "examples": [
        "/app/dashboard/eaa84cd0"
      ],
      "title": "path",
      "description": "The path component contains data, usually organized in hierarchical form, that, along with data in the non-hierarchical query component (uri.query), serves to identify a resource within the scope of the URI's scheme and naming authority (if any). The path is terminated by the first question mark (?) or number sign (#) character, or by the end of the URI."
    },
    "query": {
      "type": "string",
      "examples": [
        "_g=h@22cdd26&_a=h@ed7af2a"
      ],
      "title": "query",
      "description": "The query component is indicated by the first question mark (?) character and terminated by a number sign (#) character or by the end of the URI."
    },
    "fragment": {
      "type": "string",
      "examples": [
        "noc"
      ],
      "title": "fragment",
      "description": "The fragment identifier component of a URI allows indirect identification of a secondary resource by reference to a primary resource and additional identifying information. A fragment identifier component is indicated by the presence of a number sign (#) character and terminated by the end of the URI."
    }
  },
  "additionalProperties": false
}

=== autonubil/codex/samples/json/uri.json
{
  "ref": "http://username:password@demo.north.codex-test.org:9000/app/dashboard/eaa84cd0?_g=h@22cdd26&_a=h@ed7af2a#noc",
  "scheme": "http",
  "authority": "username:password@demo.north.codex-test.org:9000",
  "userinfo": {
    "user": "username",
    "password": "password"
  },
  "host": "demo.north.codex-test.org",
  "port": 9000,
  "path": "/app/dashboard/eaa84cd0",
  "query": "_g=h@22cdd26&_a=h@ed7af2a",
  "fragment": "noc"
}
